name: Arduino Library CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: adafruit/ci-arduino
        path: ci

    - name: Install the prerequisites
      run: bash ci/actions_install.sh

    - name: Check for correct code formatting with clang-format
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r .

#     Temporarily disable the check on documentation, as it is currently not needed at this time.
#    - name: Check for correct documentation with doxygen
#      env:
#        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
#        PRETTYNAME : "CRSF for Arduino"
#      run: bash ci/doxy_gen_and_deploy.sh

#     Temporarily disable testing on Metro M4, for now.
#     For some reason, it is returning "No such file or directory" on CRSFforArduino.h
#     Further investigation is needed.
#    - name: Test the code on supported platforms
#      run: python3 ci/build_platform.py metro_m4
